// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PETSearch.Data;

#nullable disable

namespace PETSearch.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PETSearch.Models.Animals", b =>
                {
                    b.Property<int>("Animal_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Clinic_Id")
                        .HasColumnType("int");

                    b.Property<int?>("ClinicsClinic_Id")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<int?>("LocationsLocation_Id")
                        .HasColumnType("int");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Animal_Id");

                    b.HasIndex("ClinicsClinic_Id");

                    b.HasIndex("LocationsLocation_Id");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("PETSearch.Models.Clinics", b =>
                {
                    b.Property<int>("Clinic_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Clinic_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<int?>("LocationsLocation_Id")
                        .HasColumnType("int");

                    b.HasKey("Clinic_Id");

                    b.HasIndex("LocationsLocation_Id");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("PETSearch.Models.Locations", b =>
                {
                    b.Property<int>("Location_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Location_Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("PETSearch.Models.Persons", b =>
                {
                    b.Property<int>("Person_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Animal_Id")
                        .HasColumnType("int");

                    b.Property<int?>("AnimalsAnimal_Id")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<int?>("LocationsLocation_Id")
                        .HasColumnType("int");

                    b.Property<string>("Person_Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Person_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Person_Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Person_Phone_Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Person_Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Person_Id");

                    b.HasIndex("AnimalsAnimal_Id");

                    b.HasIndex("LocationsLocation_Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("PETSearch.Models.Vets", b =>
                {
                    b.Property<int>("Vet_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Clinic_Id")
                        .HasColumnType("int");

                    b.Property<int?>("ClinicsClinic_Id")
                        .HasColumnType("int");

                    b.Property<string>("Vet_Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Vet_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Vet_Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Vet_Phone_Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Vet_Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Vet_Id");

                    b.HasIndex("ClinicsClinic_Id");

                    b.ToTable("Vets");
                });

            modelBuilder.Entity("PETSearch.Models.Animals", b =>
                {
                    b.HasOne("PETSearch.Models.Clinics", "Clinics")
                        .WithMany()
                        .HasForeignKey("ClinicsClinic_Id");

                    b.HasOne("PETSearch.Models.Locations", "Locations")
                        .WithMany()
                        .HasForeignKey("LocationsLocation_Id");

                    b.Navigation("Clinics");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("PETSearch.Models.Clinics", b =>
                {
                    b.HasOne("PETSearch.Models.Locations", "Locations")
                        .WithMany()
                        .HasForeignKey("LocationsLocation_Id");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("PETSearch.Models.Persons", b =>
                {
                    b.HasOne("PETSearch.Models.Animals", "Animals")
                        .WithMany()
                        .HasForeignKey("AnimalsAnimal_Id");

                    b.HasOne("PETSearch.Models.Locations", "Locations")
                        .WithMany()
                        .HasForeignKey("LocationsLocation_Id");

                    b.Navigation("Animals");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("PETSearch.Models.Vets", b =>
                {
                    b.HasOne("PETSearch.Models.Clinics", "Clinics")
                        .WithMany()
                        .HasForeignKey("ClinicsClinic_Id");

                    b.Navigation("Clinics");
                });
#pragma warning restore 612, 618
        }
    }
}
